name: CI/CD Pipeline para ML

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "config.yaml"
      - "requirements.txt"
      - "Makefile"
      - ".github/workflows/ml.yml"
  workflow_dispatch:

jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        python -m pytest tests/

    - name: Ejecutar entrenamiento
      run: |
        python -m src.train

    - name: Guardar artefacto de MLflow
      uses: actions/upload-artifact@v4
      with:
        name: modelo-entrenado
        path: mlruns/
